export * from "./Nav";
export * from "./Footer";
export * from "./Card";
export * from "./Head";
export * from "./Accordion";
export * from "./Tag";
export * from "./Carrousel";
export * from "./Autor";
export * from "./Rate";
